### PR TITLE
[amundsen-kube-helm] HELM Chart v1.0.0 PR

### PR DESCRIPTION
**Pull request by javamonkey79**
### Summary of Changes

HELM Chart v1.0.0;
FIXES for: ISSUE-327, ISSUE-282, ISSUE-328, ISSUE-234

* removed es, neo charts; added es dependency chart
* moved neo templates in with amundsen templates
* minor resource bug fix (328)
* lots more comments
* added minimum helm version to docs (234)

### Documentation

* readme enhanced with new table view, values file properly annotated

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely.
- [x] PR includes a summary of changes.
- [x] My commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by javamonkey79** [comment]
@lukelowery @feng-tao @samshuster

**Comment by feng-tao** [comment]
don't have much knowledge about this. will let either @samshuster or @lukelowery to review and if everything looks good, I could help to merge it :)

**Comment by javamonkey79** [comment]
Super, thanks @lukelowery ! 

I think it's good to go @feng-tao

**Comment by feng-tao** [comment]
thanks @lukelowery @javamonkey79 !

**Pull request merged**
