### PR TITLE
issue 53; k8s + helm setup for amundsen

### PR DESCRIPTION
**Pull request by javamonkey79**
### Summary of Changes

_Include a summary of changes then remove this line_

### Documentation

_What documentation did you add or modify and why? Add any relevant links then remove this line_

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely.
- [ ] PR includes a summary of changes.
- [ ] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by javamonkey79** [comment]
@feng-tao I found the cla check issue and fixed it; I've also left out the submodule part. If you want any other changes, lmk

**Comment by feng-tao** [comment]
thanks @javamonkey79 , will take a look tomorrow. I think it looks good.
cc @jinhyukchang

**Comment by feng-tao** [comment]
thanks @javamonkey79

**Comment by javamonkey79** [comment]
awesome, thanks @feng-tao !

**Pull request merged**
