### PR TITLE
Updare docker; Update roadmap

### PR DESCRIPTION
**Pull request by ttannis**
### Summary of Changes

Updated the quickstart to use the latest frontend and search library releases & updated the roadmap to reflect completed and in progress projects.

### Documentation

Updated the quickstart to use the latest frontend and search library releases & updated the roadmap to reflect completed and in progress projects.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely.
- [x] PR includes a summary of changes.
- [x] My commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by ttannis** [comment]
fyi @danwom @jinhyukchang @feng-tao

**Comment by jornh** [comment]
Whops! If I’m not mistaken (I hope I am) it looks like the frontend docker file v2.1.0 referenced here isn’t on dockerhub - but that it’s actually v2.0.0 that got pushed today: https://hub.docker.com/r/amundsendev/amundsen-frontend/tags?page=1&ordering=last_updated

Underlying reason looks like it’s because what got tagged as v2.1.0 still has version 2.0.0 in setup.py: 

https://github.com/lyft/amundsenfrontendlibrary/blob/v2.1.0/setup.py#L37

**Comment by ttannis** [comment]
Thanks fo catching this. I'll fix within the hour.

**Comment by jornh** [comment]
Similarly pypi currently has no version 2.1.0: https://pypi.org/project/amundsen-frontend/2.0.0/#history

**Comment by ttannis** [comment]
@jornh frontend `2.1.0` now exists as it should: 
https://hub.docker.com/r/amundsendev/amundsen-frontend/tags?page=1&ordering=last_updated
https://pypi.org/project/amundsen-frontend/#history

I think the one casualty is that the `2.0.0` docker image will have to be stuck with containing updated code.

**Comment by jornh** [comment]
Yes, thank you for the swift reaction!

I wonder if the v2.0.0 can be restored in a relatively safe way (either manual upload/re-tag on DockerHub alone, or if a removal of GitHub tag and retagging the same SHA. There may still be stuff referencing 2.0.0 like e.g. the helm chart and people having git checkouts. On the other hand there’s always a risk when doing stuff like that. So I’ll leave it to you to decide. It doesn’t have to be made in haste with 2.1.0 out now.

**Comment by ttannis** [comment]
> Yes, thank you for the swift reaction!
> 
> I wonder if the v2.0.0 can be restored in a relatively safe way (either manual upload/re-tag on DockerHub alone, or if a removal of GitHub tag and retagging the same SHA. There may still be stuff referencing 2.0.0 like e.g. the helm chart and people having git checkouts. On the other hand there’s always a risk when doing stuff like that. So I’ll leave it to you to decide. It doesn’t have to be made in haste with 2.1.0 out now.

Jin was also able to manually push 2.0.0 again, so I think all is now officially well.

**Comment by jornh** [comment]
Great!

**Pull request merged**
