### PR TITLE
Add some conferences

### PR DESCRIPTION
**Pull request by philippemizrahi**
### Summary of Changes

Added some conferences + links to the readme

### CODE REVIEW

**Comment by philippemizrahi** [comment]
@ttannis

**Comment by ttannis** [comment]
Looks like you did it on top of your old work, so that PR makes it look like you're adding the roadmap again. You'll have to update your branch with the latest code from `master`, then push this PR back up. (and make sure that `.DS_store` is gone. 

Let me know on slack if you need clarification about what commands to run.

**Comment by philippemizrahi** [comment]
gotcha, let me try that

**Comment by feng-tao** [comment]
+1 on @ttannis for removing the unnecessary files.

**Comment by ttannis** [comment]
> Thanks for cleaning up the history. Still have that mysterious `.DS_Store` file though. If you can delete that we're all set here.

@philippemizrahi when you get a chance

**Pull request merged**
