### PR TITLE
Add developer guide

### PR DESCRIPTION
**Pull request by ttannis**
### Summary of Changes
Addresses https://github.com/lyft/amundsen/issues/18.

This PR adds some documentation and a new `.yml` file for local development. At the moment, the local workflow we can support leverages using Docker to spin up all the necessary containers, just like in the installation. Some key pieces of information:
1. We needed a new `.yml` file that will build using the content in the local submodules, as opposed to an official tag. 
2. I ran into some issues building `amundsenfrontendlibrary` with the `public.Dockerfile`, and created a separate `local.Dockerfile`. More details in https://github.com/lyft/amundsenfrontendlibrary/pull/246 for why this was needed.

There's a lot of room for improvement, specifically surrounding the fact that rebuilding local changes in `amundsen/amundsenfrontendlibrary` takes much longer than the others, it will take a bit more research for me to understand some ways we could cut that down.  In addition, we still have to improve our dummy data for people to actually be able to use this to develop on top of existing features.

### Documentation

Added `docs/developer_guide.md`

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely.
- [x] PR includes a summary of changes.
- [x] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by ttannis** [comment]
FYI @feng-tao @jinhyukchang @danwom

**Comment by ttannis** [comment]
cc @jornh 

I believe this is pretty much the idea you had proposed, but with a new `.yml` file that captures the changes I had to make to get this working for me.

**Comment by feng-tao** [comment]
@ttannis I wonder what are the issues you run into when building the FE docker image?

**Comment by ttannis** [comment]
> @ttannis I wonder what are the issues you run into when building the FE docker image?

It's detailed in this PR, which also needs review: https://github.com/lyft/amundsenfrontendlibrary/pull/246

**Comment by ttannis** [comment]
> LGTM, but I think from time to time we need to bump the PYPI version for FE in order to push the latest code into both pypi and dockerHub.

I agree, though I'm thinking about more about a more responsible policy for frontend release so that we release versions intentionally for specific cases like:
1. Bug fixes of existing features
2. Fully completed sets of features that have had enough time to be vetted for bug or issues. 

The reason for wanting to be more cautious is that unlike with metadata and search, sometimes a hidden bug can take an entire page down. (remember a couple of those blank page issues)

Daniel and I are switching to working on feature branches instead of committing directly to master (except for bug fixes), so we should be able to have more frequent and stable releases moving forward.

**Comment by feng-tao** [comment]
sgtm! Thanks for the reply.

**Comment by jornh** [comment]
Sorry for missing the boat here (by a few minutes!)

Overall - super nice addition & findings @ttannis.

I should be able to help with cutting away some of your research on optimizing FE build performance. Will follow up separately in a new issue/PR when I can hopefully tomorrow.

**Comment by ttannis** [comment]
> Sorry for missing the boat here (by a few minutes!)
> 
> Overall - super nice addition & findings @ttannis.
> 
> I should be able to help with cutting away some of your research on optimizing FE build performance. Will follow up separately in a new issue/PR when I can hopefully tomorrow.

No problem. Consider this more of an infinite train instead of a boat, you can always hop on! If it's any help one main area is to look at surrounds caching the results of npm install to save some time. I won't be able to look into this for a bit due to the new design implementation work, but maybe these help: 
https://www.aptible.com/documentation/deploy/tutorials/faq/dockerfile-caching/npm-dockerfile-caching.html
https://stackoverflow.com/questions/35774714/how-to-cache-the-run-npm-install-instruction-when-docker-build-a-dockerfile

**Pull request merged**
